name = "CTBase"
uuid = "54762871-cc72-4466-b8e8-f6c8b58076cd"
version = "0.17.4"
authors = ["Olivier Cots <olivier.cots@irit.fr>", "Jean-Baptiste Caillau <caillau@univ-cotedazur.fr>"]

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[weakdeps]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MarkdownAST = "d0879d2d-cac2-40c8-9cee-1863dc0c7391"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[extensions]
CoveragePostprocessing = ["Coverage"]
DocumenterReference = ["Documenter", "MarkdownAST", "Markdown"]
TestRunner = ["Test"]

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = [
    "Aqua",
    "Coverage",
    "Documenter",
    "Markdown",
    "MarkdownAST",
    "OrderedCollections",
    "Test"
]

[compat]
Aqua = "0.8"
Coverage = "1"
DocStringExtensions = "0.9"
Documenter = "1"
Markdown = "1"
MarkdownAST = "0.1"
OrderedCollections = "1"
Test = "1"
julia = "1.10"
