[deps]
CTBase = "54762871-cc72-4466-b8e8-f6c8b58076cd"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
MarkdownAST = "d0879d2d-cac2-40c8-9cee-1863dc0c7391"

[compat]
CTBase = "0.17"
Coverage = "1"
Documenter = "1"
MarkdownAST = "0.1"
julia = "1.10"
