# [.github/workflows/coverage.yml]
name: Coverage
on:
  push:
    branches:
      - main
    tags: '*'
jobs:
  call:
    uses: control-toolbox/CTActions/.github/workflows/coverage.yml@main
    with:
      use_ct_registry: true
    secrets:
      codecov-secret: ${{ secrets.CODECOV_TOKEN }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
